spring:
  application:
    name: eCommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/eCommerce
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
application:
  security:
    cors:
      origin: http://localhost:5173
      max-age: 3600
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration-time: 86400000 # 1 day
server:
  port: 8080
  servlet:
    context-path: /ecommerce/api/v1